version: '3.7'
services:
  neo4j:
    image: neo4j:latest
    volumes:
      - ./data:/data
      - ./logs:/logs
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none